# Plugin recompiled by NaulbiMIX | Sponsored by FlatiCommunity (https://t.me/flaticommunity)
# Specially publication for https://teletype.in/@naulbimix/rumine
#
# Плагин разработан командой кодеров UniversalStudio для бесплатного использования.
# Если Вы обнаружите какой-либо баг, незамедлительно сообщите нам.
# Vk: vk.com/universalstudio
# Site: u-studio.su

# Права:
# ucode.code - Доступ к команде /code
# ucode.bypasslimit - Обход ограничений
# ucode.reload - Доступ к команде /codereload

codes:
    'ustudio': # Сам код, /code test test test
        limit: 1 # Макс. кол-во использований 3
        limit-players: 2 # Макс. кол-во игроков которые введут этот код
        commands: # Команды от имени консоли
            - 'eco give %player% 1000'
        message: 'Вы успешно активировали код;title: &aВуа-ля %nl% Код успешно активирован.'
        message-limit: 'Вы исчерпали лимит использования данного кода.;title: &cУпс :( %nl% Лимит изчерпан'
        message-limit-players: 'Данный промокод много раз вводили;title: &cУвы %nl% Код не доступен.'
    test2:
        limit: 1
        limit-players: 10
        commands:
            - 'axe give %player% axe1'
        message: 'Вы успешно активировали код;title: &aВуа-ля %nl% Код успешно активирован.'
        message-limit: 'Вы исчерпали лимит использования данного кода.;title: &cУпс :( %nl% Лимит изчерпан'
        message-limit-players: 'Данный промокод много раз вводили;title: &cКоды %nl% Код не доступен.'

messages:
    prefix: '&6UniversalCode &8| &f'
    no-permission: 'У вас нет прав.'
    code-notfound: 'Данный промокод не найден.'
    codereload: 'Конфигурация перезагружена.'
    code: '&6/code [код] &f- Ввести промокод'